### ISSUE TITLE
Not sure what to download

### ISSUE THREAD

**Issue by Qjeezy** [Xorlent/Orcaslicer-Qidi-Plus-4#1]
Im trying to get this plus 4 original profile ported into my orca slicer but im a little confused on what to download. 

Im using a Mac. 

When I click n the zip file it just takes me to another GitHub page. when I right click and then click download linked contents, it's giving me an html file. 

What exactly do I need to do to download this printer profile?

**Comment by Rizadium** [comment]
![image](https://github.com/user-attachments/assets/3ce4e36e-039f-4aec-a37d-b95551f93d09)
On the main page, click on Code and download zip.
Below should be a direct link:
https://github.com/Xorlent/Orcaslicer-Qidi-Plus-4/archive/refs/heads/main.zip

**Comment by Qjeezy** [comment]
Thank You!

**Comment by Xorlent** [comment]
Hi @Qjeezy, if you click the desired .ZIP file, it will take you to a screen with an empty text window.
[Here is a direct link to the Modified profiles download page](https://github.com/Xorlent/Orcaslicer-Qidi-Plus-4/blob/main/Qidi%20X%204%20Series%20Modified%20Gcode.zip)  
[Here is a direct link to the stock profiles download page](https://github.com/Xorlent/Orcaslicer-Qidi-Plus-4/blob/main/Qidi%20X%204%20Series%20Original.zip)

Click the download icon above the empty window to download the .ZIP.  I hope this helps!
![Screencap](https://github.com/user-attachments/assets/be199a95-d79e-4a5a-a4c8-375da2a38eb8)

**Comment by Xorlent** [comment]
@Rizadium thanks!
